churn_pipeline:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: dev
      schema: dev_ocelik
      host: dbc-d93ecbbd-cf6c.cloud.databricks.com
      http_path: /sql/1.0/warehouses/35f22ecad1c625f5
      token: "{{env_var('DBT_ENV_SECRET_DATABRICKS_TOKEN')}}"

    prod:
      type: databricks
      catalog: prod
      schema: dbo
      host: dbc-d93ecbbd-cf6c.cloud.databricks.com
      http_path: /sql/1.0/warehouses/35f22ecad1c625f5
      token: "{{env_var('DBT_ENV_SECRET_DATABRICKS_TOKEN')}}"
      threads: 4